"""pyecflow - A Python package for creating ecFlow workflows.

This package provides high-level classes and utilities for building ecFlow
workflows using pyflow. It includes components for creating suites, families,
anchor families, and tasks, as well as utilities for reading package data
and generating suite definitions.

Main Components
---------------
WorkflowSuite : class
    Top-level container for ecFlow workflows.
WorkflowFamily : class
    Family container for organizing tasks and sub-families.
WorkflowAnchorFamily : class
    Anchor family for synchronizing tasks across workflows.
WorkflowTask : class
    Basic unit of work representing a single job or script.
generate_suite : function
    Generate ecFlow suite definition files and deploy scripts.
read_package_file : function
    Utility for reading package data files (static files and templates).

Attributes
----------
__version__ : str
    Version string for the pyecflow package.

Examples
--------
>>> from pyecflow import WorkflowSuite, WorkflowTask
>>> suite = WorkflowSuite('my_suite')
>>> context = {'variables': {'VAR1': 'value'}, 'script': 'script.sh'}
>>> task = WorkflowTask('my_task', context)
"""

from __future__ import absolute_import

import importlib.resources

from .generate_suite import generate_suite
from .workflow_anchorfamily import WorkflowAnchorFamily
from .workflow_family import WorkflowFamily
from .workflow_suite import WorkflowSuite
from .workflow_task import WorkflowTask


def read_package_file(filetype: str, filename: str) -> str:
    """Read a file from the package data.
    Parameters
    ----------
    filetype : str
        The type of file to read, either 'static' or 'templates'.
    filename : str
        The name of the file to read.
    Returns
    -------
    str
        The contents of the file.
    Raises
    ------
    FileNotFoundError
        If the file does not exist.
    """

    try:
        with importlib.resources.path("pyecflow", filetype) as data_path:
            file = data_path / filename
            contents = file.read_text()
            return contents
    except FileNotFoundError:
        raise FileNotFoundError(f"File {filename} not found in {filetype}.")


try:
    # NOTE: the `_version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from ._version import __version__
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = ""

__all__ = ["read_package_file", "__version__", "WorkflowTask", "WorkflowAnchorFamily", "generate_suite"]
