from __future__ import absolute_import

import importlib.resources

from .workflow_task import WorkflowTask


def read_package_file(filetype: str, filename: str) -> str:
    """Read a file from the package data.
    Parameters
    ----------
    filetype : str
        The type of file to read, either 'static' or 'templates'.
    filename : str
        The name of the file to read.
    Returns
    -------
    str
        The contents of the file.
    Raises
    ------
    FileNotFoundError
        If the file does not exist.
    """

    try:
        with importlib.resources.path("pyecflow", filetype) as data_path:
            file = data_path / filename
            contents = file.read_text()
            return contents
    except FileNotFoundError:
        raise FileNotFoundError(f"File {filename} not found in {filetype}.")


try:
    # NOTE: the `_version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from ._version import __version__
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = ""

__all__ = ["read_package_file", "__version__", "WorkflowTask"]
