"""pyecflow - A Python package for creating ecFlow workflows.

This package provides high-level classes and utilities for building ecFlow
workflows using pyflow. It includes components for creating suites, anchor
families, and tasks, as well as utilities for reading package data and
deploying suite definitions.

Main Components
---------------
WorkflowSuite : class
    Top-level container for ecFlow workflows. Includes a generate_suite() method
    to create suite directory structure and deploy files.
WorkflowAnchorFamily : class
    Anchor family for organizing workflow hierarchy. Use generate_anchor_families()
    to create family structures under a suite.
WorkflowTask : class
    Task definition within a workflow. Use generate_tasks() to populate anchor
    families with tasks.
read_package_file : function
    Utility for reading package data files (static files and templates).

Attributes
----------
__version__ : str
    Version string for the pyecflow package.

Examples
--------
>>> from pyecflow import WorkflowSuite
>>> from pyecflow.workflow_task import WorkflowTask
>>> suite = WorkflowSuite('my_suite', host=pf.LocalHost('localhost'))
>>> suite.add_anchor_family()  # Creates default family hierarchy
>>> WorkflowTask.generate_tasks(suite)  # Populates families with tasks
>>> suite.generate_suite(suite_dir='/path/to/suite')
"""

from __future__ import absolute_import

import importlib.resources

from .workflow_anchorfamily import WorkflowAnchorFamily
from .workflow_suite import WorkflowSuite
from .workflow_task import WorkflowTask


def read_package_file(filetype: str, filename: str) -> str:
    """Read a file from the package data.
    Parameters
    ----------
    filetype : str
        The type of file to read, either 'static' or 'templates'.
    filename : str
        The name of the file to read.
    Returns
    -------
    str
        The contents of the file.
    Raises
    ------
    FileNotFoundError
        If the file does not exist.
    """

    try:
        with importlib.resources.path("pyecflow", filetype) as data_path:
            file = data_path / filename
            contents = file.read_text()
            return contents
    except FileNotFoundError:
        raise FileNotFoundError(f"File {filename} not found in {filetype}.")


try:
    # NOTE: the `_version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from ._version import __version__
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = ""

__all__ = ["read_package_file", "__version__", "WorkflowSuite", "WorkflowAnchorFamily", "WorkflowTask"]
