family_A:
  tasks: {}
  children:
    family_Aa:
      tasks: {}
      children: {}
    family_Ab:
      tasks: {}
      children: {}

family_B:
  tasks: {}
  children:
    family_Ba:
      tasks: {}
      children: {}
