name: pyecflow
channels:
  - conda-forge
dependencies:
  - python
  - numpy>=1.21
  - pyyaml>=6.0
  - jinja2>=3.1.2
  - ecflow>=5.13
  - pip
  - pip:
    - wxflow
    - pyflow-workflow-generator>=3.4.1
variables:
  QT_MAC_WANTS_LAYER: 1
