channels:
  - conda-forge

dependencies:
  - python
  - pip
  - numpy
  - pyyaml
  - jinja2
  - ecflow
  - pytest
  - pip:
    - git+https://github.com/ecmwf/pyflow@3.1.0

variables:
  QT_MAC_WANTS_LAYER: 1
